### ISSUE TITLE
Проблема на DLE 11.1 с отправкой сообщений

### ISSUE THREAD

**Issue by Gagaman** [Gameerr/Ene-Pm#1]
Привет. скажи как быть в таком случае?
[https://youtu.be/ALb3C_etoeQ](url)

**Comment by Gagaman** [comment]
видимо дело в IonCube Loader. так как все требования кроме IonCube Loader присутствуют.
Хостинг: hostinger.ru, он вроде по умолчанию поддерживает его. не понимаю в чем может быть ещё косяк?)

**Comment by Gameerr** [comment]
Здравствуйте, какая кодировка ? IonCube здесь не причем, он не нужен и ни один файл не закодирован.

**Comment by Gagaman** [comment]
кодировка utf-8. DLE 11.1

**Comment by Gagaman** [comment]
PHP версия: 5.5

**Comment by Gameerr** [comment]
Откройте консоль браузера и посмотрите что пишет в нем. Консоль браузера открывается сочетанием клавиш Ctrl+Shift+I

**Comment by Gagaman** [comment]
справа кнопка с иконкой пользователя. я нажимаю и открывается пустое окно в котором поиск. Ввожу логин второго админа и слева открывается диалоговое окно для переписки. я вписываю текст и при нажатии на Enter не отправляется. можно там поставить кнопку "отправить"?

**Comment by Gagaman** [comment]
консоль чистая. без ошибок =)

**Comment by Gagaman** [comment]
ой. стоп. не . зависла видимо, загружалось. да, действительно там ошибки

**Comment by Gagaman** [comment]
Uncaught TypeError: d.widget is not a function
ene_pm.min.js: 2

Uncaught TypeError: $(...).draggable is not a function
localhost/browser.js:44

Opera has modified script or content on www.youtube.com (PATCH-1185, youtube.com - show video above playlist). See browser.js for details (program):1

'webkitOfflineAudioContext' is deprecated. Please use 'OfflineAudioContext' instead.

chrome-extension://enhhojjnijigcajfphajepfemndkmdlo/cast_sender.js
Failed to load resource: net::ERR_FAILED

chrome-extension://fmfcbgogabcbclcofgocippekhfcmgfj/cast_sender.js
Failed to load resource: net::ERR_FAILED

chrome-extension://fjhoaacokmgbjemoflkofnenfaiekifl/cast_sender.js
Failed to load resource: net::ERR_FAILED

**Comment by Gameerr** [comment]
Вы не верно подключили скрипты. ene_pm.min.js должен идти самый последний после всех подключенных скриптов, и обязательно перед закрывающим тегом `</body>` не подключайте их в `<head>`

**Comment by Gagaman** [comment]
а вот main.tpl

`<!DOCTYPE html>
<html>
<head>
{headers}
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
<link rel="stylesheet" href="{THEME}/css/font-awesome.min.css">
<link rel="stylesheet" href="{THEME}/css/bootstrap.min.css">
<link rel="stylesheet" href="{THEME}/css/AdminLTE.min.css">
<link rel="stylesheet" href="{THEME}/css/skins/_all-skins.min.css">
<link href="https://fonts.googleapis.com/css?family=Roboto+Condensed:300,400,700&amp;subset=cyrillic" rel="stylesheet">
<link rel="shortcut icon" href="{THEME}/images/favicons/favicon.png">
<link rel="apple-touch-icon" href="{THEME}/images/favicons/57x57.png">
<link rel="apple-touch-icon" sizes="72x72" href="{THEME}/images/favicons/72x72.png">
<link rel="apple-touch-icon" sizes="114x114" href="{THEME}/images/favicons/114x114.png">
<link rel="stylesheet" type="text/css" href="{THEME}/css/flexslider.css" media="screen">
<link rel="stylesheet" type="text/css" href="{THEME}/css/magnific-popup.css" media="screen">

<script src="http://yastatic.net/jquery/2.1.1/jquery.min.js"></script>
<script type="text/javascript">
  window.onload = function () {
      jQuery("#user-city").text(ymaps.geolocation.city);
      jQuery("#user-region").text(ymaps.geolocation.region);
	  jQuery("#user-country").text(ymaps.geolocation.country);
  }
</script>
<script src="http://api-maps.yandex.ru/2.0-stable/?load=package.standard&lang=ru-RU" type="text/javascript"></script>
[desktop]
	[not-group=5]
		<link media="screen" href="{THEME}/ene_pm/front_end/style.css" type="text/css" rel="stylesheet" />
		<link href="{THEME}/ene_pm/front_end/jquery.jscrollpane.css" type="text/css" rel="stylesheet">
	[/not-group]
[/desktop]
</head>

<body class="hold-transition skin-green sidebar-mini layout-boxed cubik">
{AJAX}
<div class="wrapper">
{include file="modules/catmenu.tpl"}
<div class="content-wrapper">
{speedbar}

<section class="content">
<div class="row">

<form action="#" method="get" class="sidebar-form">
<div class="input-group">
<input type="text" name="q" class="form-control" placeholder="Поиск по словам..">
<span class="input-group-btn">
<button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
</button>
</span>
</div>
</form>
</div>
[available=main]{include file="modules/pagetools.tpl"}[/available]
<div class="row">{info}{content}</div>
<hr><br>
[banner_servise]{banner_servise}[/banner_servise]
</section>
</div>

<footer class="main-footer">
<div class="pull-right hidden-xs">Все права защищены!</div>
<strong>&copy; 2016-2017</strong>
</footer>

<div class="control-sidebar-bg"></div>
</div>

{include file="feedback-modal.tpl"}

<script src="{THEME}/js/bootstrap.min.js"></script>
<script src="{THEME}/js/slimScroll/jquery.slimscroll.min.js"></script>
<script src="{THEME}/js/fastclick/fastclick.js"></script>
<script src="{THEME}/js/app.min.js"></script>
<script type="text/javascript" src="{THEME}/js/jquery.migrate.js"></script>
<script type="text/javascript" src="{THEME}/js/script.js"></script>
<script type="text/javascript" src="{THEME}/js/jquery.isotope.min.js"></script>
<script type="text/javascript" src="{THEME}/js/jquery.magnific-popup.min.js"></script>
[desktop]
	[not-group=5]
		{include file="engine/modules/ene_pm/ene_pm.php"}
		<script type="text/javascript" src="{THEME}/ene_pm/front_end/jquery.jscrollpane.min.js"></script>
		<script type="text/javascript" src="{THEME}/ene_pm/front_end/jquery.mousewheel.js"></script>
		<script type="text/javascript" src="{THEME}/ene_pm/front_end/ene_pm.min.js"></script>
		<script type="text/javascript" src="{THEME}/ene_pm/front_end/jquery.notify.min.js"></script>
		<link rel="stylesheet" type="text/css" href="{THEME}/ene_pm/front_end/ui.notify.css" />
		{include file="engine/modules/ene_pm/ajax/notify.php"}
	[/not-group]
[/desktop]
</body>
</html>`

**Comment by Gameerr** [comment]
Замените ene_pm.min.js на ene_pm.js если проблема не пройдет, значит конфликт скриптов и скорее проблема в jquery.migrate

**Comment by Gagaman** [comment]
ой я извиняюсь. в общем у меня и так под всеми скриптами перед </body> стоят скрипты

**Comment by Gagaman** [comment]
а можно поставить кнопку "отправить" в диалоговом окне?
И почему при заполнении сообщения placeholder так и остается? Это можно убрать?

**Comment by Gameerr** [comment]
Он должен убираться, в течении часа выйдет обновление. Как повторяюсь может быть проблема в jquery.migrate. Кнопки отправить - не будет.

**Comment by Gagaman** [comment]
я ввожу текст в диалоговом окне и при нажатии Enter он спускается вниз. CTRL+ENTER и SHIFT+ENTER тоже самое

**Comment by Gagaman** [comment]
я убрал jquery.migrate проблема так и осталась. может потому что аякс не подключен?

**Comment by Gameerr** [comment]
Тег {AJAX} ?

**Comment by Gagaman** [comment]
Не.. тег {AJAX} под открывающимся <body>. Я имею ввиду про библиотеку

**Comment by Gameerr** [comment]
вы убрали стандартную dle jquery с подключения ?

**Comment by Gagaman** [comment]
да

**Comment by Gameerr** [comment]
Какую тогда поставили ?

**Comment by Gagaman** [comment]
Верите или нет. я только что все скрипты перед закрывающим BODY убрал и так сохранил. все равно не робит

**Comment by Gameerr** [comment]
Скрипты, я имел ввиду только те что идут в модуле а не прям все что у вас на сайте.

**Comment by Gagaman** [comment]
https://youtu.be/XDV2R_fGRHI - залил скин с экрана. посмотрите. 2 варианта попробовал.

**Comment by Gagaman** [comment]
видео только залил. через пару сек будет доступен к просмотру

**Comment by Gagaman** [comment]
https://youtu.be/XDV2R_fGRHI - вот

**Comment by Gagaman** [comment]
видимо косяк в сборке. возможно версия не та или всё из-за ionCube?

**Comment by Gameerr** [comment]
Консоль покажите во время отправки сообщения. Желательно скрин а не копипаст текста. Я уже писал IonCube в обще здесь не нужен.

**Comment by Gagaman** [comment]
ок. сек

**Comment by Gagaman** [comment]
http://i11.pixs.ru/storage/9/1/2/hLxjpg_7509147_24293912.jpg

**Comment by Gagaman** [comment]
ну или тут: http://uploads.ru/XMZ1c.jpg

**Comment by Gameerr** [comment]
Подключите стандартный jquery что идет вместе с dle.

**Comment by Gagaman** [comment]
lib.js ?

**Comment by Gagaman** [comment]
подключил. так же все..

**Comment by Gagaman** [comment]
может проблема из-за стандартных скриптов DLE?

**Comment by Gagaman** [comment]
т.е "разрешить посетителям делиться полезными новостями?"

**Comment by Gagaman** [comment]
не.. так же всё

**Comment by Gagaman** [comment]
я залил всё содержимое и прописал все как надо. либо сборка кривая попалась либо в настройках что-то потому что скрипты тут не причем. пробовал без них и всё так же..

**Comment by Gagaman** [comment]
есть какое нибудь спасение?

**Comment by Gagaman** [comment]
может проблема в .tpl?

**Comment by Gameerr** [comment]
Проблема в ваших скриптах. Не более. Модуль работает исправно, это связано с тем что у вас подключены скрипты которые могут вызывать проблему в работе модуля а так же правки которые могли нарушить работу. К примеру функция .draggable доступна в стандартном jquery.js что идет вместе с dle.

**Comment by Gagaman** [comment]
решил проблему...) пздц полный.
я прошу меня извинить. проблема была в скрипте от яндекса который я посадил в шапке.
данный скрипт был предназначен для указания города.

**Comment by Gagaman** [comment]
спасибо. всё работает от души) очень вам благодарен) и ещё раз sorry
