### ISSUE TITLE
Работа модуля на мобильных устройствах

### ISSUE THREAD

**Issue by apelisin** [Gameerr/Ene-Pm#2]
Ещё раз здравствуйте. Я писал на DLE FAQ по поводу доработок модуля, платно. Можно адаптировать данный модуль под работу на мобильных устройствах, а точнее его внешний вид. Спасибо заранее за ответ.

**Comment by Gameerr** [comment]
О мобильной версии будет речь, сразу после того как модуль будет переписан на socket
