### ISSUE TITLE
Работа модуля Ene-Pm-master на DLE 11.2

### ISSUE THREAD

**Issue by apelisin** [Gameerr/Ene-Pm#3]
Доброго времени суток. При установке модуля Ene-Pm 2 на версию DLE 11.2 выдаёт ошибку.

\engine\inc\ene_pm.php on line 82

Моете подсказать, как исправить? Спасибо заранее.

**Comment by Gameerr** [comment]
У вас версия PHP ниже 5.4

**Comment by apelisin** [comment]
Большое спасибо за быстрый ответ. Да, версия 5,3 у меня. С нетерпением жду переписанного модуля под моб устройства. Обязательно приобрету его себе, очень мне он будет к стати в моб шаблоне.

**Comment by Gameerr** [comment]
Модуль не будет платным.

**Comment by apelisin** [comment]
Я бы с удовольствием отблагодарил, пусть модуль и будет бесплатным. Спасибо большое за ответы на мои вопросы.
